### ISSUE TITLE
FontScaleObservable

### ISSUE THREAD

**Issue by learwebit** [Notalib/nativescript-accessibility-ext#17]
In your README.md file, you wrote:
![image](https://user-images.githubusercontent.com/32451798/53298498-a428ba00-3837-11e9-8648-ac1a0266fd5b.png)
But I cannot understand how to use in this observable.
Can you supply an example?

Thanks in advance!

**Comment by m-abs** [comment]
Hi @learwebit 

The `FontScaleObservable` is a `NativeScript` Observable, not a `rxjs` one. That might be the confusion here.

You should be able to use it like this:
```typescript
const fontSizeObserver = new FontScaleObservable();

fontSizeObserver.on(Observable.propertyChangeEvent, (args: PropertyChangeData) => {
    if (args.propertyName === FontScaleObservable.FONT_SCALE) {
       // Possible iOS values: 0.5, 0.7, 0.85, 1, 1.15, 1.3, 1.5, 2, 2.5, 3, 3.5, 4
       // Possible Android values: 0.85, 1, 1.15, 1.3
       const fontScale = args.value;
       .... use value....
    }
});
```

We use it internally to set the `a11y-fontscale-*` classes on the `Page`:
https://github.com/Notalib/nativescript-accessibility-ext/blob/master/src/ui/page/page.ts#L21

I hope that helps, otherwise you're welcome to catch me tomorrow on the NativeScript slack under the handle `m_abs`.
