### ISSUE TITLE
AccessibilityRole="Header" does not enable for navigation between headers in TalkBack.

### ISSUE THREAD

**Issue by oslc15** [Notalib/nativescript-accessibility-ext#38]
### Problem Description
Setting the role to header on a label element does not enable the TalkBack feature  navigating between headers on a screen. TalkBack is not able to find any headers on the page.

iOS works if you add the `accessibilityTraits="header"`

### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.4.2
- Cross-platform modules: ^5.4.3
- Runtime(s):         
       "tns-ios": {
            "version": "5.4.2"
        },
        "tns-android": {
            "version": "5.4.0"
        }
- Plugin(s):  "@nota/nativescript-accessibility-ext": "^5.4.0",

### Please, tell us how to recreate the issue in as much detail as possible. 
Use the flag `accessibilityRole="header"`, enable Talkback and navigate to the view with the header element. Select title mode and try to navigate to the header.

### Is there any code involved? 
```
<Label title="Example Header" accessible="true" accessibilityRole="header" />
```

**Comment by m-abs** [comment]
Hi @oslc15 

You're using the 5.x version of the plugin.`accessibilityRole` is part of the API for the 6+ version of the plugin that is still in alpha.

With NativeScript 6.x we decided to change the API, because the old one was too verbose and didn't do what we needed.

You can't mark an element as a header on android with version 5.x of the plugin.
